### PR TITLE
#250 deleting invoices doesnt work

### LINKED ISSUE #250: Bug: deleting invoices doesn't work
I changed the api to be more like what I expect from the backend - a single `deleteInvoice` mutation rather than what we had been using: `deleteInvoices`

I forgot and this broke deleting invoices in the list view.

Fortunately a PR I was waiting for in graphql-request was merged and a release cut 7 hours ago which will make this nice and easy.

https://github.com/prisma-labs/graphql-request/releases

Which means that after upgrading, instead of some cumbersome string creation, we will be able to simple do something like:

```
const data = await batchRequests(endpoint, [
    { document, variables },
    { document, variables },
    { document, variables },
])
```

### PR DESCRIPTION
**Pull request by josh-griffin**
Fixes #250

### CODE REVIEW

File: packages/mock-server/src/api/mutations.ts [hunk 1]
```diff
@@ -76,18 +77,24 @@ export const update = {
...
     });
 
-    return db.remove.invoice(invoice);
+    return db.remove.invoice(invoiceId);
   },
-  invoiceLine: (invoiceLine: InvoiceLine): InvoiceLine => {
+  invoiceLine: (invoiceLineId: string): string => {
+    const invoiceLine = ResolverService.byId.invoiceLine(invoiceLineId);
+
+    if (!invoiceLine.stockLineId) {
```
Comment (mark-prins) [inline packages/mock-server/src/api/mutations.ts:92]: Not required?

File: packages/mock-server/src/worker/handlers.ts [hunk 2]
```diff
@@ -28,16 +28,14 @@ const insertInvoice = graphql.mutation(
 );
 
 const deleteInvoices = graphql.mutation(
```
Comment (mark-prins) [inline packages/mock-server/src/worker/handlers.ts:30]: :nit this should now be `deleteInvoice`

**Review by mark-prins — APPROVED** [review]
LGTM!

It looks all good - I'm having trouble running this branch, the `mock-server` is complaining about the `window` global in config which seems strange. I thought we could merge and I'll revisit later if that's still a problem
