### PR TITLE
Query Params tests

### LINKED ISSUE #1204: Cannot delete the Outbound shipment
### Step to reproduce

- Setup remote-server, Central server, Web-client
- Login to Web-client
- Create a dummy Outpatient invoice, add a line then delete the line save it
- View the Outpatient list
- Find that Outpatient shipment
- Select it and click `Delete selected lines`  from the option DDL
- It asked to `Select the line / lines`, but is already selected

Screen Shot 2022-04-29 at 1 45 54 PM

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1204 

Migrates the tests for `useQueryParams` and drops the stories, which I think aren't very helpful.

### CODE REVIEW

File: packages/common/src/ui/layout/tables/context/TableContext.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ const TableProvider = <T extends RecordWithId>({
 }: PropsWithChildren<{
   initialStore?: UseBoundStore<TableStore>;
   createStore: () => UseBoundStore<TableStore>;
-  queryParamsStore?: UseBoundStore<QueryParamsState<T>>;
+  queryParamsStore: UseBoundStore<QueryParamsState<T>>;
```
Comment (mark-prins) [inline packages/common/src/ui/layout/tables/context/TableContext.tsx:45]: thought that I'd make this required to prevent potential errors when calling the hook

File: packages/common/src/utils/regex/RegexUtils.test.ts [hunk 2]
```diff
@@ -76,6 +76,6 @@ describe('String matching for object properties', () => {
 
   describe('escapeChars', () => {
     expect(RegexUtils.escapeChars('a')).toBe('a');
-    expect(RegexUtils.escapeChars('about[ ]time')).toBe('about time');
+    expect(RegexUtils.escapeChars('about[ ]time')).toBe('about\\[ \\]time');
```
Comment (mark-prins) [inline packages/common/src/utils/regex/RegexUtils.test.ts:79]: 🤔  I'd already updated this. must be languishing in a branch somewhere.

File: packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx [hunk 3]
```diff
@@ -19,7 +20,15 @@ const Expando = ({
   const expandoColumns = useExpansionColumns();
 
   if ('lines' in rowData && rowData.lines.length > 1) {
-    return <MiniTable rows={rowData.lines} columns={expandoColumns} />;
+    return (
+      <MiniTable
+        rows={rowData.lines}
+        columns={expandoColumns}
+        queryParamsStore={createQueryParamsStore<StocktakeLineFragment>({
+          initialSortBy: { key: 'expiryDate' },
```
Comment (mark-prins) [inline packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx:28]: not that this will do anything, we're not refetching here. really just a nicety, and potentially useful if the hook is called and the sort options requested for a manual sort.

File: packages/common/src/hooks/useQueryParams/usePagination.stories.tsx [hunk 4]
```diff
@@ -1,43 +0,0 @@
-// import React from 'react';
```
Comment (clemens-msupply) [inline packages/common/src/hooks/useQueryParams/usePagination.stories.tsx:1]: I was already wondering the last PR what are these stories?

**Review by clemens-msupply — APPROVED** [review]
Looks good to me. Sorry for not providing more feedback in the last PRs but think I am not deep enough in the code base yet...

File: packages/common/src/hooks/useQueryParams/usePagination.stories.tsx (hunk 4 above)
Comment (mark-prins) [reply packages/common/src/hooks/useQueryParams/usePagination.stories.tsx:1]: the stories are a way to showcase / demonstrate components using storybook. To run locally, use `yarn storybook` or for the slightly easier version.. it is hosted on demo: https://demo-open.msupply.org:6006/

The idea is to show the scope of available components, which helps prevent developers creating duplicates, and to show the various options available within components.

**Comment by mark-prins** [comment]
thanks for the reviews @clemens-msupply! and sorry for the long winded refactory PRs.. they can be tedious to try and review at the best of times

File: packages/common/src/hooks/useQueryParams/usePagination.stories.tsx (hunk 4 above)
Comment (clemens-msupply) [reply packages/common/src/hooks/useQueryParams/usePagination.stories.tsx:1]: thanks!
