### PR TITLE
Language detection order

### LINKED ISSUE #1241: Changing language in Admin view doesn't work
☝️
Needed for Madagascar demo on Thursday 🙏

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1241 
Oops. Update the language detection order, so that localStorage is before the new custom navigator detection 🙄

### CODE REVIEW

**Comment by clemens-msupply** [comment]
Maybe its just my tablet but now the normal login name gets converted to lower case, e.g. Admin -> admin...

**Review by CarlosNZ — APPROVED** [review]
Ah -- that looks more relevant to the issue! 😆

File: packages/common/src/intl/context/IntlContext.tsx [hunk 1]
```diff
@@ -47,12 +47,11 @@ export const IntlProvider: FC<PropsWithChildrenOnly> = ({ children }) => {
         defaultNS,
         detection: {
           order: [
-            'omsBrowserLanguageDetector',
             'querystring',
             'cookie',
             'localStorage',
             'sessionStorage',
-            'navigator',
```
Comment (clemens-msupply) [inline packages/common/src/intl/context/IntlContext.tsx:55]: Is removing the navigator correct?

Comment (mark-prins) [reply packages/common/src/intl/context/IntlContext.tsx:55]: the custom detector is a theft of the navigator code, so I thought that we didn't need to duplicate 😉

**Comment by mark-prins** [comment]
> Maybe its just my tablet but now the normal login name gets converted to lower case, e.g. Admin -> admin...

Argh! sorry 🤷  can't see why that would happen. I've only added the autocapitalize hint to the intialise screen. The login is a separate component. 
Maybe it's time to do this issue? https://github.com/openmsupply/remote-server/issues/745
