### PR TITLE
remove counts from mocks

### LINKED ISSUE #649: Update schema for stock counts
The stock counts changes were merged to in the API, time to update. Currently getting
`Error: Unable to merge GraphQL type "Queries": Field "stockCounts" already defined with a different type. Declared as "StockCounts", but you tried to override with "StockCountsResponse` from the mock server

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #649

### CODE REVIEW

File: packages/common/src/types/schema.ts [hunk 1]
```diff
@@ -419,6 +414,12 @@ export type DeleteSupplierRequisitionResponseWithId = {
   response?: Maybe<DeleteSupplierRequisitionResponse>;
 };
 
+export type EqualFilterBigNumberInput = {
+  equalAny?: InputMaybe<Array<Scalars['Int']>>;
+  equalTo?: InputMaybe<Scalars['Int']>;
+  notEqualTo?: InputMaybe<Scalars['Int']>;
+};
```
Comment (joshxg) [inline packages/common/src/types/schema.ts:421]: Are we not allowed to use little numbers? So many limitations of this api 😱

**Review by joshxg — APPROVED** [review]
Nice, thanks

File: packages/common/src/types/schema.ts (hunk 1 above)
Comment (mark-prins) [reply packages/common/src/types/schema.ts:421]: 😄  I missed that! Is `Int` a 'BigNumber' then?
