### PR TITLE
#560 Cant create supplier requisitions

### LINKED ISSUE #560: Supplier requisition new requisition button is broken
The new requisition button in the supplier requisition list view doesn't do anything when clicked

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #560 

- Not sure how I missed this. I think relatively simple - adding the name modal and corrected the api

### CODE REVIEW

File: packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx [hunk 1]
```diff
@@ -63,10 +70,40 @@ export const SupplierRequisitionListView: FC = () => {
...
+              otherPartyId: name?.id,
+            };
+
+            try {
+              const result = await onCreate(requisition);
+              invalidate();
+              navigate(result);
+            } catch (e) {
+              const errorSnack = error(
+                'Failed to create invoice! ' + (e as Error).message
```
Comment (mark-prins) [inline packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx:96]: a little nit picky - I wouldn't expect the requisition page to be creating an invoice 😜

**Review by mark-prins — APPROVED** [review]
👍  that works! not sure how I missed that earlier.. soz

File: packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx (hunk 1 above)
Comment (joshxg) [reply packages/requisitions/src/SupplierRequisition/ListView/ListView.tsx]: Done! Though I just merged and realised I shouldve done a translation not fix the string.. oops!
